#!/usr/bin/env python
# encoding: utf-8


####Created by Denny C. Ng on Feb 23, 2015
#Copyright @Tsinghua University

import sys, os, os.path, shutil
from datetime import date, time, datetime, timedelta
import time

from spiValidation import isFileValide as validation

import MySQLdb


s = os.sep
#rootpath on the server 'MotionX'
root = "/home/chaowu/spice/buffer"
spiceRoot = "/home/chaowu/data/spice/usage_statistics"
backupRoot = "/home/chaowu/data/spice/source_files"
waitingRoot = "/home/chaowu/spice/waiting"
unknownRoot = "/home/chaowu/data/spice/unknown_files"
maliciousRoot = "/home/chaowu/data/spice/malicious_files"
experimentRoot = '/home/chaowu/data/spice/experiment'

MySQLAddr = 'addr'
MySQLUser = 'usr'
MySQLPass = 'pass'
MySQLDB = 'db'

MAX_DEVICE_FOR_PER_USER = 5

#rootpath on my Mac OS X
#root = "/Users/Chao/Code/PythonDeamon/files"
#spiceRoot = "/Users/Chao/Code/PythonDeamon/usage_statistics"
#backupRoot = "/Users/Chao/Code/PythonDeamon/source_files"
#experimentRoot = '/Users/Chao/Code/PythonDeamon/experiment'

############### MYSQL DATABASE  HANDELER SOURCE CODE ####################

def dbTest():
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        cursor.execute("SELECT VERSION()")
        data = cursor.fetchone()
        print "Database version : %s " % data
        db.close()
        
        
def dbSelection(twitter_id, rec_uuid):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        
        sql = "SELECT * FROM TWIDERE \
               WHERE twitter = '%s'"  % (twitter_id)
        try:
           cursor.execute(sql)
           results = cursor.fetchall()
           if results is not None:
               for row in results:
                       if row[1] == rec_uuid:
                           return 0
                       else:
                           continue
                       
               return 1
           elif results is None:
               return None  
                                     
        except:
           print "Error: unable to fecth data"
           #database or table errors
           return 2
       
        finally:
                db.close()
        
def dbSelectUUID(twitter_id):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        
        sql = "SELECT * FROM TWIDERE \
               WHERE twitter = '%s'" % (twitter_id)
        try:
           cursor.execute(sql)
           results = cursor.fetchall()
           if results is not None:
                   for row in results:
                           return row[1]  
                                     
        except:
           print "Error: unable to fecth data"
           #database or table errors
       
        finally:
                db.close()

def dbSelectTwitter(device_uuid):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        
        sql = "SELECT * FROM TWIDERE \
               WHERE uuid = '%s'" % (device_uuid)
        try:
           cursor.execute(sql)
           results = cursor.fetchall()
           if results is not None:
                   for row in results:
                           return row[0]  
                                     
        except:
           print "Error: unable to fecth data"
           #database or table errors
       
        finally:
                db.close()
        
                
                
def dbInsertion(twitter_id, device_id):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        
        sql = "INSERT INTO TWIDERE(twitter, \
               uuid, check_in) \
               VALUES ('%s', '%s', CURDATE())" % \
               (twitter_id, device_id)
        try:
           cursor.execute(sql)
           db.commit()
        except:
           # Rollback in case there is any error
           db.rollback()
           
        finally:
                db.close()
        

                        
def getTwitterByUUID(device_id):
        res = dbSelectTwitter(device_id)
        if res is not None:
                return res
        elif res is None:
                return None

def getUUIDbyTwitter(twitter_id):
        res = dbSelectUUID(twitter_id)
        if res is not None:
                return res
        elif res is None:
                return None
  
              
def isTwitterExist(twitter_id):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        
        sql = "SELECT * FROM TWIDERE \
               WHERE twitter = '%s'" % (twitter_id)
        try:
           cursor.execute(sql)
           results = cursor.fetchall()
           if results is not None:
                   for row in results:
                           return row[0]
           else:
                   return None 
                                     
        except:
           print "Error: unable to fecth data"
           #database or table errors
        
        finally:
                db.close()
                
   
def isPairExist(twitter_id, device_id):
        res = dbSelection(twitter_id, device_id)
        if res is None:
                #dbInsertion(twitter_id, device_id)
                #return device_id
                return None
        else:
                return res

def getUUIDBindCount(twitter_id):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        sql = "SELECT COUNT(uuid) FROM TWIDERE \
               WHERE twitter = '%s'" % (twitter_id)
        try:
           cursor.execute(sql)
           results = cursor.fetchone()[0]
           if results is not None:
               return results
           else:
               return None
                                     
        except:
           print "Error: unable to fecth data"
           #database or table errors
       
        finally:
                db.close()

def insertUUIDMaping(origin, replaceUUID):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        
        sql = "INSERT INTO UUIDMAP(original, \
               maping) \
               VALUES ('%s', '%s')" % \
               (origin, replaceUUID)
        try:
           cursor.execute(sql)
           db.commit()
        except:
           # Rollback in case there is any error
           db.rollback()
           
        finally:
                db.close()
        
    

def isUUIDinMaping(uuid):
        db = MySQLdb.connect(MySQLAddr, MySQLUser , MySQLPass, MySQLDB)
        cursor = db.cursor()
        
        sql = "SELECT * FROM UUIDMAP \
               WHERE original = '%s'" % (uuid)
        try:
           cursor.execute(sql)
           results = cursor.fetchall()
           if results is not None:
                   for row in results:
                           return row[1]
           else:
                   return None 
                                     
        except:
           print "Error: unable to fecth data"
           #database or table errors
           return None
        
        finally:
                db.close()
        
          


#########################################################################


####################FILE HANDLER SOURCE CODE##############################

def log(records):
        #print 'start file classfing job...'
        try:
            file_object = file(spiceRoot + '/datalog.log','a')
            file_object.write(records + '\n')
        finally:
            file_object.close()


def isPathExist(rootPath, name):
        if os.path.isdir(rootPath + '/' + name):
            pass
        else:
            os.mkdir(rootPath + '/' + name)


def writeFile(file, str):
        try:
            fp = open(file, 'a')
            fp.write(str) 
        finally:       
            fp.close()

    

def writeUserActionFile(path, action, behavior):
        if action == 'Words':
            writeFile(path + '/' + 'Subscribe_History.txt', behavior )
        elif action == 'Preview':
            writeFile(path + '/' + 'Subscribe_History.txt', behavior )
        elif action == 'PreviewM':
            writeFile(path + '/' + 'Subscribe_History.txt', behavior )
        elif action == 'PreviewO':
            writeFile(path + '/' + 'Subscribe_History.txt', behavior )
        elif action == 'Clicked':
            writeFile(path + '/' + 'Subscribe_History.txt', behavior )
        elif action == 'Favor':
            writeFile(path + '/' + 'Favorite_History.txt', behavior )
        elif action == 'Unfavor':
            writeFile(path + '/' + 'Favorite_History.txt', behavior )
        elif action == 'Visit':
            writeFile(path + '/' + 'Link_Clicked_History.txt', behavior ) 
        elif action == 'Refresh':
            writeFile(path + '/' + 'Refresh_History.txt', behavior ) 
        elif action == 'Tweet':
            writeFile(path + '/' + 'Publish_History.txt', behavior ) 
        elif action == 'Media':
            writeFile(path + '/' + 'Publish_History.txt', behavior )
        elif action == 'Retweet':
            writeFile(path + '/' + 'Publish_History.txt', behavior )
        elif action == 'RetweetM':                                 
            writeFile(path + '/' + 'Publish_History.txt', behavior )
        elif action == 'RetweetO':                                 
            writeFile(path + '/' + 'Publish_History.txt', behavior )
 


def readFileinRow(mFile, storePath, fileType):
        file = open(mFile)
        for line in file:
            if fileType == 'Network':
                writeFile(storePath + '/' + 'Network.txt', line)
            elif fileType == 'onWifi':
                writeFile(storePath + '/' + 'onWifi.txt', line)
            elif fileType == 'onLaunch':
                writeFile(storePath + '/' + 'onLaunch.txt', line)
            elif fileType == 'Location':
                writeFile(storePath + '/' + 'Location.txt', line)
            elif fileType == 'App':
                writeFile(storePath + '/' + 'App.txt', line)
            else:
                action = line.split(',')[1]
                writeUserActionFile(storePath, action, line)
        file.close()
        
        
def fileDistribution(profile, uuid, fType):
        shutil.copyfile(root + '/' + profile, backupRoot + '/' + profile)                       
        readFileinRow(root + '/' + profile, spiceRoot + '/' + uuid + '/' + fType, fType)        
        os.remove(root + '/' + profile)


def waitingFileDistribution(profile, uuid, fType):                       
        readFileinRow(waitingRoot + '/' + profile, spiceRoot + '/' + uuid + '/' + fType, fType)        
        os.remove(waitingRoot + '/' + profile)
        
        
def fileMovetoWaiting(profile):
        shutil.copyfile(root + '/' + profile, waitingRoot + '/' + profile)    
        shutil.copyfile(root + '/' + profile, backupRoot + '/' + profile)       
        os.remove(root + '/' + profile)
        
def fileMoveToUnknown(profile):
        shutil.copyfile(waitingRoot + '/' + profile, unknownRoot + '/' + profile)       
        os.remove(waitingRoot + '/' + profile)

        
def fileMoveToUnknownDirectly(profile):
        shutil.copyfile(root + '/' + profile, backupRoot + '/' + profile)
        shutil.copyfile(root + '/' + profile, unknownRoot + '/' + profile)       
        os.remove(root + '/' + profile)
        
def maliciousDefence(profile):
        log('[remove malicious file directly]: ' + profile)
        shutil.copyfile(root + '/' + profile, maliciousRoot + '/' + profile)
        os.remove(root + '/' + profile)


def typeHandler(uuid):
        twitter = getTwitterByUUID(uuid)
        if twitter is None:
                return None
        else:
                return twitter


def SOURCE_FILE_HANDLE():
        for name in os.listdir(root):
            if os.path.isfile(os.path.join(root,name)):
                if len(name.split('-')) > 1:
                    log('[handle file in buffer folder]: ' + name)
                    if validation(name) == False:
                            maliciousDefence(name)
                            continue
                    fileTime = name.split('-')[0]
                    fileName = name.split('-')[1]
                    machineUUID = fileName.split('_')[0]
                   
                    #isPathExist(spiceRoot, machineUUID)
                    fileType = fileName.split('_')[1]
                    if machineUUID == 'unknown' or machineUUID == 'null':
                            fileMoveToUnknownDirectly(name)
                            continue
                    #get accurate UUID from MySQL database Table TWIDERE
                    if fileType == 'App' or fileType == 'Location' or fileType == 'Network' or fileType == 'onLaunch' or fileType == 'onWifi':
                           ret_of_UUID =  typeHandler(machineUUID)
                           if ret_of_UUID is not None:
                                   pass
                           elif ret_of_UUID is None:
                                   fileMovetoWaiting(name)
                                   continue
                                   #don't know the file from where
                                       
                    else:
                            ret_of_Twitter = isTwitterExist(fileType)
                            if ret_of_Twitter is None:
                                    dbInsertion(fileType, machineUUID)
                            elif ret_of_Twitter is not None:
                                    ret =  isPairExist(fileType, machineUUID) 
                                    if ret == 0:
                                            pass
                                    elif ret == 1 or ret == None or ret ==2:                                           
                                            deviceNum = getUUIDBindCount(fileType)
                                            if deviceNum is not None:
                                                    if deviceNum < MAX_DEVICE_FOR_PER_USER:
                                                            dbInsertion(fileType, machineUUID)    
                                                    else:
                                                            maping_MachineUUID = getUUIDbyTwitter(fileType)
                                                            insertUUIDMaping(machineUUID, maping_MachineUUID)
                                                            machineUUID = maping_MachineUUID
                                            elif deviceNum is None:
                                                    dbInsertion(fileType, machineUUID)
                                                
                                                        
                                            
                    #receiving experiment files
                    isPathExist(spiceRoot, machineUUID)
                    isPathExist(spiceRoot, machineUUID + '/' + fileType)
                    fileDistribution(name , machineUUID, fileType)
        
        time.sleep(5)
       
        ##### handl the waiting folder ##########
        
        for name in os.listdir(waitingRoot):
            if os.path.isfile(os.path.join(waitingRoot,name)):
                if len(name.split('-')) > 1:
                    log('[handle file in waiting folder]: ' + name)
                    fileTime = name.split('-')[0]
                    fileName = name.split('-')[1]
                    machineUUID = fileName.split('_')[0]
                    fileType = fileName.split('_')[1]
                    #get accurate UUID from MySQL database Table TWIDERE
                    ret_of_UUID =  typeHandler(machineUUID)
                    if ret_of_UUID is not None:
                            pass
                    elif ret_of_UUID is None:
                            ret = isUUIDinMaping(machineUUID)
                            if ret is not None:
                                    machineUUID = ret
                            elif ret is None:
                                    fileMoveToUnknown(name)
                                    continue
                                    #don't know the file from where                  
                    #receiving experiment files
                    isPathExist(spiceRoot, machineUUID)
                    isPathExist(spiceRoot, machineUUID + '/' + fileType)
                    waitingFileDistribution(name , machineUUID, fileType)

    

def runTask(func, day=0, hour=0, min=0, second=0):
        # get current time 
        now = datetime.now()
        strnow = now.strftime('%Y-%m-%d %H:%M:%S')
        print "now:",strnow
        #log('[task start] on ' + strnow)
        # get net_run time
        period = timedelta(days=day, hours=hour, minutes=min, seconds=second)
        next_time = now + period
        strnext_time = next_time.strftime('%Y-%m-%d %H:%M:%S')
        print "next run:",strnext_time
        func()
        #log('[task done] on ' +  datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
        while True:
            time.sleep(1)
            now = datetime.now()
            strnow = now.strftime('%Y-%m-%d %H:%M:%S')
            # if system time eq next_time run the specific task(hello func)
            if str(strnow) == str(strnext_time):
                log('[task start] on ' + strnow)
                print 'Task start....'
                print "now:",strnow
                print "next run on",(now+period).strftime('%Y-%m-%d %H:%M:%S')
                func()
                print "task done."
                strnext_time = (now + period).strftime('%Y-%m-%d %H:%M:%S')
                log('[task done] on ' +  datetime.now().strftime('%Y-%m-%d %H:%M:%S'))

#########################################################################


if __name__ == "__main__":
        # do the UNIX double-fork magic, see Stevens' "Advanced 
        # Programming in the UNIX Environment" for details (ISBN 0201563177)
        try: 
            pid = os.fork() 
            if pid > 0:
                # exit first parent
                sys.exit(0) 
        except OSError, e: 
            print >>sys.stderr, "fork #1 failed: %d (%s)" % (e.errno, e.strerror) 
            sys.exit(1)
        # decouple from parent environment
        os.chdir("/") 
        os.setsid() 
        os.umask(0) 
        # do second fork
        try: 
            pid = os.fork() 
            if pid > 0:
                # exit from second parent, print eventual PID before
                print "Daemon PID %d" % pid
                log("Daemon PID %d" % pid) 
                sys.exit(0) 
        except OSError, e: 
            print >>sys.stderr, "fork #2 failed: %d (%s)" % (e.errno, e.strerror) 
            sys.exit(1) 
        # start the daemon main loop
        #main()
        runTask(SOURCE_FILE_HANDLE, hour = 12)
